### ISSUE TITLE
Association sometimes returns a hash

### ISSUE THREAD

**Issue by pezholio** [contentful/contentful_model#114]
I have two models, `BlogPost` and `Comment`

```
class BlogPost < ApplicationRecord
  self.content_type_id = 'blogPost'
  
  belongs_to_many :comments
end
```

```
class Comment < ApplicationRecord
  self.content_type_id = 'comment'
  
  has_one :associated_record, class_name: 'BlogPost'
end
```

A `BlogPost` has many `Comments`, and this seems to work most of the time. However, when running my tests, from time to time, when I try and get the associated blog post from a comment, `ContentfulModel` returns a hash, rather than the actual model:

```
post = BlogPost.create(title: slug, subheading: 'subheading', date: Date.today, slug: slug, body: 'Some Text', author: author)
post.publish
comment = Comment.create(name: 'foo', email: 'foo@bar.baz', organisation: '', comment: 'Hello', associated_record: post)
comment.publish
comment.associated_record
#=> {"sys"=>{"type"=>"Link", "linkType"=>"Entry", "id"=>"4GX6dhjbrGGwYu8IKiC4Ma"}}
```

Any ideas as to where I'm going wrong?

**Comment by dlitvakb** [comment]
Hey @pezholio,

Which version of the gem are you using?

Cheers

**Comment by pezholio** [comment]
1.0.0 👍

**Comment by dlitvakb** [comment]
@pezholio It's because what you get as a response from `create` and `publish` is a CMA object, there the references are not hydrated. If you want the full reference, you should do `Comment.find(comment.id).associated_record`, which is the CDA object.

Cheers

**Comment by pezholio** [comment]
Ah, that makes sense, thanks! 👍
