### ISSUE TITLE
Using migrations without a database

### ISSUE THREAD

**Issue by pezholio** [contentful/contentful_model#115]
I have a project that isn't backed by a database, so can't use the migrations module as set out in the examples. Is this something I'll have to build from scratch, or is there an existing solution kicking around that I may not have seen? 

I've found the (not supported by Contentful) [contentful-migrations.rb](https://github.com/monkseal/contentful-migrations.rb) gem, but this has a dependency on the older version of the contentful-management gem, so I can't really use it.

**Comment by dlitvakb** [comment]
Hey @pezholio,

The migrations of this gem are completely decoupled from `ActiveRecord` itself, the examples show how to use them with `ActiveRecord` because it's the most common use-case.

You can use them just like:

```ruby
require 'contentful_model'

class AddNameToAuthor
  include ContentfulModel::Migration::Migrations

  def up
    add_content_type_field 'author', 'name', :symbol
  end
end

AddNameToAuthor.new.up
```

Hope this helps,

Cheers

**Comment by pezholio** [comment]
Cool, that's awesome. I'll have a look and see how I get on 👍 There may be some reusable logic around rake tasks etc that I can contribute back.
