### ISSUE TITLE
coerce_field not working

### ISSUE THREAD

**Issue by aldreth** [contentful/contentful_model#121]
I have an event content model that has a `datetime` field that I want to coerce into a `Datetime`

```
class Contentful::Event < ContentfulModel::Base
  self.content_type_id = 'event'

  coerce_field datetime: :Date
end
```

When I call `datetime` on an event instance I get the error `no implicit conversion of DateTime into String`

Somehow, the value of the field is coerced twice, once on initialization & the second time on accessing the value. The second time https://github.com/contentful/contentful.rb/blob/master/lib/contentful/coercions.rb#L64 throws the error as it tries to parse an already coerced value.

I've added a PR with a failing test - #120.

**Comment by dlitvakb** [comment]
Thanks @aldreth I'll take a look into this.

Cheers

**Comment by dlitvakb** [comment]
This has been now fixed and merged.

Cheers

**Comment by aldreth** [comment]
Thanks very much @dlitvak.
