### ISSUE TITLE
provide link to usage documentation for find_by filtering

### ISSUE THREAD

**Issue by zrisher** [contentful/contentful_model#14]
In `README.md`:

> find_by([hash])
> Accepts a hash of options to include in the search, as similar as possible to ActiveRecord version...

and in `lib/contentful_model/chainable_queries.rb`:

```
# if the search is a hash, use the key to specify the search field operator
# For example
# Model.search(start_date: {gte: DateTime.now}) => "fields.start_date[gte]" => DateTime.now
```

I can't find documentation on the ActiveRecord version that functions with hash options like `:gte`. Could you please provide a link to somewhere that shows us all the parameters we can use? Apologies if this is simple for other rails users, it's been a while, but I'm having trouble finding it digging through their documentation and your code base.

**Comment by edtjones** [comment]
hi @zrisher yeah - sorry - I think the README is behind the code. Will update ASAP.

**Comment by zrisher** [comment]
No worries, thanks for this gem! Using it successfully in multiple production environments.
