### ISSUE TITLE
How to get locale entries ?

### ISSUE THREAD

**Issue by vivekmalikymca** [contentful/contentful_model#27]
how can we get locale specific entries ? when we are saying **foo.all.load** - Will it fetch for default locale or all ?

**Comment by dlitvakb** [comment]
Hey @vivekmalikymca,

Currently it will only search for `default_locale`, but I can adding multi-locale searching as well.

I'll add it to our roadmap and address it as soon as I can.

In the meantime, you can add it yourself by doing:

```ruby
module ContentfulModel
  module LocalizedQueries
    def self.included(base)
      base.extend ClassMethods
    end

    module ClassMethods
      def locale(locale_code)
        @query << { locale: locale_code }
        self
      end
  end
end

class MyModel < ContentfulModel::Base
  include ContentfulModel::LocalizedQueries

  # your code
end
```

Hope this helps
