### ISSUE TITLE
Cache busting

### ISSUE THREAD

**Issue by ericgross** [contentful/contentful_model#29]
I need to bust the cache when the data in Contentful is changed, I suppose via a webhook.

How can I tell my models to throw away the cache (perhaps for only for certain content) and go back to the API?

**Comment by dlitvakb** [comment]
Hey @ericgross,

I assume you're using contentful/contentful_rails along with this gem.

If that's the case, then you should be able to do: `YourModel.clear_cache_for(your_entry.cache_key)`

Hope that helps

**Comment by ericgross** [comment]
I am not using contentful_rails - it doesn't look like a gem I want to import. I'd like to do this without the contentful_rails gem.

**Comment by dlitvakb** [comment]
Hey @ericgross,

Without using `contentful_rails`, this gem does not have any caching by itself, `contentful_rails` is a package that works on top of this one, which one of it's features is adding Caching to `ContentfulModel::Base` models

Hope that helps

**Comment by ericgross** [comment]
Thanks - my caching was happening because of partial caching, not at this layer.
