### ISSUE TITLE
The .order() method does not accept sys properties

### ISSUE THREAD

**Issue by pmoore** [contentful/contentful_model#45]
According to [Contentful Delivery API docs](https://www.contentful.com/developers/docs/references/content-delivery-api/#/reference/search-parameters/order) we can sort by sys properties as well as field names: 

```
Both the sys properties (such as sys.createdAt) or field values (such as fields.myCustomDateField) can be used for ordering.
```

The current `.order()` method only implements the `order` query hash with "fields".  As a workaround, we're currently the `params(order: '-sys.updatedAt')` to get us where we need to go, but would like to just user the order method as we are elsewhere.

I have a PR open for a possible refactor to make this possible https://github.com/contentful/contentful_model/pull/41

**Comment by dlitvakb** [comment]
This has been merged

Cheers

PS: Sorry it took a bit long!
