### ISSUE TITLE
`all` only returns the first 100 records

### ISSUE THREAD

**Issue by clowder** [contentful/contentful_model#48]
Seems that by default `all` only returns the first 100 records. Options would be:

1. Document the implicit limit
2. Remove the limit and just return everything in one go
3. Add pagination to the API

Thoughts?

----

To get around the issue I re-implemented an all with an arbitrarily massive number...

```ruby
class Post < ContentfulModel::Base
  def self.all
    params('limit' => 1_000_000).load
  end
end
```

**Comment by dlitvakb** [comment]
Hey @clowder,

The API allows up to a `limit: 1000`.

To fetch everything, the gem provides the methods, `#limit` and `#skip` to fetch any amount you need.

Just make sure that if you are skipping records, to always use it in conjunction with an ordering attribute like `sys.updatedAt`, in the gem can be called as `Model.order('updatedAt').limit(1000).skip(1000)`.

Hope that helps,

Cheers

**Comment by clowder** [comment]
@dlitvakb Great! Thanks for the quick reply.
