### ISSUE TITLE
Can't sort by publishedAt - others work

### ISSUE THREAD

**Issue by Frexuz** [contentful/contentful_model#51]
```
@blog_posts = CMS::BlogPost.all.order('publishedAt').load #nope

@blog_posts = CMS::BlogPost.all.order('updatedAt').load #works

module CMS
  class BlogPost < ContentfulModel::Base

    self.content_type_id = 'blogPost'

  end
end

```

Any idea?

**Json preview in Contentful:**
![screenshot](https://cloud.githubusercontent.com/assets/49692/20917854/da2d4ca2-bbce-11e6-9510-6a1d1e61b9c7.png)

**Update:**
Seems that key isn't included in `Contentful::Resource::SystemProperties:: SYS_COERCIONS`. What to do?

**Comment by clowder** [comment]
I hit this today too.

I actually extended

**Comment by clowder** [comment]
I hit this today too.

I actually [extended](https://github.com/stowbotics/contentful.rb/tree/published-at) `SYS_COERCIONS` to include the published timestamps, and got another error that indicates that the API doesn't allow ordering by published:

> Contentful::BadRequest – The property "sys.firstPublishedAt" is invalid when querying a published Entry

I couldn't find anything in the API docs that lays out what fields you can/cannot sort by. Would be great to get some clarification.

**Comment by clowder** [comment]
Seems that the set of system things you can order by is bounded to the ["common resource attributes"](https://www.contentful.com/developers/docs/references/content-delivery-api/#/introduction/common-resource-attributes).

FYI, my use case here was the company blog.

**Comment by dlitvakb** [comment]
Hey @clowder and @Frexuz,

What @clowder says seems to be the reason, I'll ask the platform team if this is the case.

I'll get back to you shortly on this.

Cheers

**Comment by dlitvakb** [comment]
After talking with the lead developer of our platform team I got this issue clarified.

`sys.publishedAt` is only available for searching on the CMA, and exclusively for already published entries.

This integration only does search over CDA, so the property is unavailable to be searched.

Does that make sense?

**Comment by clowder** [comment]
Makes sense, might be a nice one to add to the CDA. For now we have added our own `publishedAt` field.

**Comment by dlitvakb** [comment]
Hey @clowder,

`sys.updatedAt` should match the latest published value, as anything present in the CDA is published, the last update is the last published version of the entry.

Cheers

PS: Closing the issue, we can continue discussing about it though.

**Comment by reidcooper** [comment]
Would like to query the CDA with the `publishedAt` attribute

**Comment by dlitvakb** [comment]
Hey @reidcooper,

The `publishedAt` property is only part of the CMA. The equivalent parameter for CDA would be `sys.updatedAt`, which coincides with the `sys.publishedAt` from CMA.

Cheers
