### ISSUE TITLE
"fields" not getting set correctly?  New getters return instance of `Contentful::Link` when reference is missing or empty

### ISSUE THREAD

**Issue by pmoore** [contentful/contentful_model#54]
So I understand that Contentful's association schema will not go back and remove existing associations to an entry when that entry is removed.  For example, if I have a Post entry that references a Category and I later go and delete the category entry from Contentful then my Post entry will still have a "Link" to the dead category ID.  

That's fine for us, for now.  However, these gems (I believe) are meant to filter out these "Contentful::Link" entries when deserializing the associations and creating objects.  I've noticed that this is not happening anymore.   I mentioned this in #40, it looks to be because of this change https://github.com/contentful/contentful_model/commit/35053665a74e7d8512d2ecdad3fee7839d6b07ac#diff-4a8a1bd3b58710c02288eee36bb77fdbR10.  Drilling into it, any instance of `ContentfulModel::Base` will define getters for _all_ `fields` which override any getters you may be trying to use with the `has_one` or `has_many` class methods. 

My guess is that whatever is setting up the `fields` attribute is incorrectly including those `Contentful::Link` entries.  On top of that, I'm not sure we should doing the `define_getters` for attributes/associations that we're trying to set up with `has_many` or `has_one`, seems conflicting.

**Comment by pmoore** [comment]
I guess I'm a little confused of the need for those `define_getter` methods.  Looks like that defines singleton methods for each of the fields that's returned from the API, but that seems to go against the purpose of `method_missing` in base.rb, which seems to filter out those Contentful::Link types appropriately.

**Comment by dlitvakb** [comment]
Hey @pmoore,

You're correct, I overlooked the relationships unintentionally and caused this to happen.

We're about to release the 2.0.0 version of the Contentful SDK (it is currently going through the last round of code review), which will change the base Contentful::Entry to a more simplified (and better working) object, after that is done, I will re-write a big part of this library to take advantage of the new simplified objects and fix relationships properly.

Cheers

**Comment by dlitvakb** [comment]
One question, regarding `Link` objects. There are 2 instances in which this can happen:

* Include level doesn't reach up to that level of nested objects
* Entry/Asset was deleted but Reference is still there

There currently is no way to figure which one of these cases is happening without issuing an extra request.

What would you prefer to happen:

* Issue an extra request to try to solve the link, `nil` if nothing returned
* Just `nil` regardless

Cheers

**Comment by pmoore** [comment]
Hey @dlitvakb, I think it makes sense to avoid making those API calls since and let the client be responsible for loading the necessary levels of nested children.  So I guess returning nil would be the best option?

On that note, do you know if there is any plan to have the Contentful API/backend handle the case of removing references when an entry/asset is deleted?  I think you guys are working with a nosql db so I get why it's happening.  It would just drastically help clean up scenarios like this, plus I know it's hard on editors/admins to have to go in and look for those references whenever they remove something.

**Comment by dlitvakb** [comment]
Hey @pmoore,

Back-references are a planned feature, I'm not entirely sure how is it going to be implemented, but I think it would solve this issue.

Cheers

**Comment by pmoore** [comment]
Awesome, looking forward to that.  In that case, I definitely would think returning `nil` for this scenario makes sense.  

Looking forward to 2.0 !
