### ISSUE TITLE
Presence Validator Broken for Declared fields?

### ISSUE THREAD

**Issue by pmoore** [contentful/contentful_model#62]
It looks like the `validates_presence_of :field_name` validator isn't working for fields that were declared in has_one, has_many, or return_nil_for_empty.  Digging into it, I think this is because the validator does a `respond_to?(:field_name)`, which evaluates to true in these cases.

I have a PR to update that validator and also call `.present?`:
https://github.com/contentful/contentful_model/pull/61

**Comment by dlitvakb** [comment]
This has been merged!

Cheers
