### ISSUE TITLE
Cannot attach a contentful model as a polymorphic object for another belongs_to

### ISSUE THREAD

**Issue by coleturner** [contentful/contentful_model#63]
Let's say I have this example model:

```ruby
class Activity < ApplicationRecord
  belongs_to :object, polymorphic: true
end
```

And I want to attach a contentful model as `object`.

```sh
$ ex = Activity.new
$ ex.object = Article.first
```

In order to facilitate this and allow for saving, I had to add the following methods to my *Article* class:

```ruby
class Article < ContentfulBase
  self.content_type_id = "article"

  def self.primary_key
    :id
  end

  def self.base_class
    Article
  end

  def falsifier
    false
  end

  alias :marked_for_destruction? falsifier
  alias :destroyed? falsifier
  alias :new_record? falsifier

  def _read_attribute(field_name)
    return id if field_name == self.class.primary_key
    method_missing(field_name)
  end
end
```

Unfortunately, this will save but it will not allow me to access `Activity.object` as it complains about the lack of `arel_table`

I am wondering if there is anything in the pipeline to facilitate this sort of polymorphic relational behavior - to make Contentful Model more like ActiveRecord with relations? Thanks for your time.

**Comment by dlitvakb** [comment]
Hey @colepatrickturner,

This sounds like an awesome idea for a new feature.

Would you be interested in working with me on implementing it?

Cheers

**Comment by colepatrickturner** [comment]
Hey!

I'm interested in any way I can, but months have gone by and I do not recall the issue regarding the lack of `arel_table`

The best educated guess I can give is that when Rails is selecting the association `*.object` it uses the relational table to lookup the entity, wherein this will need to be overridden so that it can be patched into a ContentfulModel.

**Comment by dlitvakb** [comment]
No problem.

Thanks for the help, if I have any issues when implementing it I'll try to reach out to you for input.

There is no ETA for this to be added, but it's already in our backlog to tackle within the next few months.

Cheers

**Comment by reidcooper** [comment]
Is there the ability to use polymorphic associations?

**Comment by dlitvakb** [comment]
Hey @reidcooper,

The answer is complicated, as it is both yes and no. And which answer you get depends on the usage pattern you want to accomplish.

So, for the positive case, if you don't define the relationships for fields that have polymorphic relationships, the `contentful.rb` gem, will automatically resolve the classes for you and solve this issue without doing anything. That said, you loose some of the capabilities that are added by this gem when explicitly defining the relationship.

For the negative case, if you really, really need that extra functionality, it's not currently going to work for polymorphic relationships, as it does redefine the accessors for those relationships.

Hope this explains the issue a bit further.

Cheers
