### ISSUE TITLE
uninitialized constant Contentful::DynamicEntry

### ISSUE THREAD

**Issue by Frexuz** [contentful/contentful_model#64]
When booting the app

```
/Users/kristiangerardsson/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:94:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'contentful_model'. (Bundler::GemRequireError)
Gem Load Error is: uninitialized constant Contentful::DynamicEntry
Backtrace for gem load error is:
/Users/kristiangerardsson/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/contentful_model-771c484bb219/lib/contentful_model/base.rb:2:in `<module:ContentfulModel>'
/Users/kristiangerardsson/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/contentful_model-771c484bb219/lib/contentful_model/base.rb:1:in `<top (required)>'
```

rails 5.0.2
contentful 2.0.0
contentful_model 0.2.0 (git master)

updated from contentful 0.12.0, so adding `gem 'contentful', '0.12.0'` works fine

**Comment by plexus** [comment]
Seems DynamicEntry is gone in the 2.0.0 version of contentful.rb, so contentful_model will need to be updated.

Would be good if someone from Contentful could comment on this. /ping @dlitvakb

**Comment by dlitvakb** [comment]
Hey @plexus and @Frexuz,

This is planned to be updated, we're gradually updating all gems depending on the CDA SDK to use 2.0.0

Cheers

**Comment by dlitvakb** [comment]
Hey @plexus and @Frexuz,

The initial PR for the 2.0 upgrade is coming out tomorrow and a formal release within the next few weeks after the review process is finished.

Cheers
