### ISSUE TITLE
ContentfulModel::Base doesn't provide a #hash method

### ISSUE THREAD

**Issue by georgebrock** [contentful/contentful_model#65]
`ContentfulModel::Base` doesn't provide a `#hash` method, so model instances cannot be effectively used as keys in Hashes, or easily filtered for duplicates.

For example, I have a `Requirement` model which `has_one` `Category`. After loading my requirements, I group them by category:

```ruby
requirements.group_by(&:category)
  # => {<Category> => [<Requirement>, <Requirement>, …], …}
```

For the results of a single query, this works fine. However, sometimes I want to combine the results of two queries, to simulate a logical `OR`:

```ruby
(some_requirements + other_requirements).uniq.group_by(&:category)
```

This throws up two problems, both arising from the lack of `#hash`:

1. Duplicate requirements from the two queries are different objects, and since they inherit the default implementation of `#hash`, they're not filtered out by `#uniq`.
2. Any category that was present in both sets of results ends up as two different keys in the resulting Hash, again because they are different objects.

## Possible solutions

In my app, I added `#hash` and `#eql?` methods based closely on [ActiveRecord's implementation][1]:

```ruby
  def eql?(other)
    super || other.instance_of?(self.class) && id.present? && other.id == id
  end

  def hash
    if id.present?
      self.class.hash ^ id.hash
    else
      super
    end
  end
```

[1]: https://github.com/rails/rails/blob/e79a991ccfdf3b7b56562be35b996e61d7395861/activerecord/lib/active_record/core.rb#L441-L457

**Comment by dlitvakb** [comment]
Hey @georgebrock,

Thanks for the suggestion, I'm currently implementing the upgrade to the 2.0 CDA SDK and implemented a similar solution to this.

The release will be coming up in the next few weeks, with the initial PR coming out tomorrow.

Cheers
