### ISSUE TITLE
Content type caching in upcoming version?

### ISSUE THREAD

**Issue by ludwick** [contentful/contentful_model#66]
There doesn't seem to be any way to get at the underlying HTTP client to add caching to it (or swap out with a different HTTP client). But I noticed that the library is not caching content type definitions, so if you have some model method that uses the content type to do something with your data (example, though not our pattern: get the full set of available fields, for example, which might not be present on a particular entry)  then it makes a network call for the content type definition for the content type id repeatedly. 

The underlying contentful client library actually does a full content types scan at start of world (limited to 1000 results) but that data is never used for content type definitions that I can tell. In practice, you'd deploy new code to take advantage of most content type changes, so it seems really weird that the gems don't cache this data somehow.

I realize there's a re-write in process to use the 2.0 contentful.rb gem (we're on a set of gems compatible with the old version), so maybe you're already thinking about this, but given that a user of this gem is explicitly modeling types for each content type, it would make sense to just outright cache content type definition response data somewhere. Is there a breakdown of what's planned to change to use the 2.0-compliant client gem?

**Comment by dlitvakb** [comment]
Hey @ludwick,

As you said this is already taken care of in the 2.0 upgrade. Which I'm currently doing right now.

The initial PR with the upgrade will be coming out tomorrow, and the official release will be within the next few weeks after the review process is finished.

Cheers

**Comment by ludwick** [comment]
Yes!!! Thank you. I'll be checking this out.

**Comment by dlitvakb** [comment]
Hey @ludwick,

This has not been released yet, but you can use the `master` branch which includes the full rewrite and upgrade.

I'm going on vacations for the next month, but I'll pick the remaining issues to be fixed before the next release as soon as I'm back. And make a release as soon as I can.

Cheers
