### ISSUE TITLE
Queries return ::Array instead of Contentful::Array

### ISSUE THREAD

**Issue by plexus** [contentful/contentful_model#67]
In the code of `Contentful::Query`

``` ruby
    def execute
      query = @parameters.merge(default_parameters)
      result = client.send(:entries,query) #=> result is a Contentful::Array
      result.items.reject! { |entity| entity.is_a?(Contentful::Link) || entity.invalid? } #=> result is a regular Array
      result
    end
```

This is problematic because it loses the metadata of the collection size. A dev on the project I work on wrote this just to get the count of articles

``` ruby
    @total_pages = ::ContentfulArticle.limit(1000).count / per_page
```

Which ended up doing a ~22s query on every page load. I ended up hacking up a custom solution like this:

``` ruby
class ContentfulArticle < ContentfulModel::Base
  def self.count
    client.entries({ 'content_type' => content_type_id, 'limit' => 0 }).total
  end
```

It might be nice to add a `count` class method to models by default.

**Comment by dlitvakb** [comment]
Hey @plexus,

Thanks for the suggestion, I'm currently working on the upgrade to the 2.0 CDA SDK and I've already implemented this.

A release will be coming up in the next few weeks (most likely next week), with the initial PR coming out tomorrow.

Cheers
