### ISSUE TITLE
RuntimeError (implicit argument passing of super from method defined by define_method() is not supported. Specify all arguments explicitly.)

### ISSUE THREAD

**Issue by mimmo** [contentful/contentful_model#73]
The error happens in this line
https://github.com/contentful/contentful_model/blob/68f0c8a0379bd983e485fbdff738e37b93ae32a8/lib/contentful_model/base.rb#L124

On my Contentful Entry _Page_ I have a field _parent_ . The home page has the parent field not set. 
To manage the Exception i added this line
```return_nil_for_empty :parent```

With or without that line i get the RuntimeError
```RuntimeError (implicit argument passing of super from method defined by define_method() is not supported. Specify all arguments explicitly.):```

I saw that in the previous version of the gem, the super method was called with parentheses
```super()```
and it worked for me

**Comment by dlitvakb** [comment]
Hey @mimmo,

Thanks for the report, will add that change prior to next release.

Cheers
