### ISSUE TITLE
Content type IDs

### ISSUE THREAD

**Issue by nomasprime** [contentful/contentful_model#80]
When I create a content type with migrations the ID is a hash but if I do it in the web client the ID is the name in lowercase.

Problem with the hash is I then have to look this up in the web client to put in the model and if run on another machine it will change again, i.e., not redeployable.

Is there a way to set the content type ID in the migration?

What's the best practice?

**Comment by nomasprime** [comment]
@dlitvakb any suggestions?

**Comment by dlitvakb** [comment]
Hey @nomasprime,

It's a bit hacky, but you can do it the following way:

```ruby
create_content_type('Some Name') do |content_type|
  management_content_type = content_type.instance_variable_get(:@management_content_type)
  management_content_type.id = 'someId'
end.publish
```

I'll add to my backlog a task to polish this and be able to set the ID without having to manually fetch the underlying management object, this will be included in the 1.0.0 release that's planned. And will soon be available in `master` while I'm working on the remaining tasks before the 1.0.0 release.

Let me know if this helps,

Cheers

**Comment by nomasprime** [comment]
Thanks @dlitvakb, that would be great.

I tried your suggestion, I get `undefined method 'id=' for nil:NilClass`.

**Comment by nomasprime** [comment]
Throwing a `content_type.save` in line 2 populates `@management_content_type` and the migration runs successfully. Suspect this might hit the API twice though, need to dig deeper into the code.

**Comment by dlitvakb** [comment]
Yeah, it looks that a change is required in order to make it work,

I'll have this on a PR today before EOD, and merged between today and Monday.

Then you can use `master` on your gemfile.

Cheers

**Comment by nomasprime** [comment]
Legend! Very much appreciated @dlitvakb 🙌

**Comment by dlitvakb** [comment]
This has just been merged.

You can now use the latest `master` version to make use of this feature.

Now by default it will have the `camelCased` version of the name you set. If you want a different ID, you can set it by doing:

```ruby
create_content_type('Some Name') do |content_type|
  content_type.id('foobar')
  # ... other stuff here ...
end.publish
```
