### ISSUE TITLE
Using migrations to set options

### ISSUE THREAD

**Issue by nomasprime** [contentful/contentful_model#81]
Can I set things like locale and validations, like required field, through migrations?

**Comment by dlitvakb** [comment]
Hey @nomasprime ,

You can do something like:

```ruby
create_content_type('some_name') do |content_type|
  field = content_type.field('field_name', :symbol)
  field.required = true
end.publish
```

Same would go for validations, anything that you can do with a `Contentful::Management::Field` you can do with the field returned from the builder.

This way you can manipulate some extra options for the fields, that the other simplified syntax does not allow for. The downside, is that it's a lot more verbose.

Hope this helps,

Cheers

**Comment by nomasprime** [comment]
Hi @dlitvakb, it does, thanks.

Presumably I'd have to use `Contentful::Management::Validation` directly in the migration as this isn't part of `Contentful::Model` yet?

Don't suppose you have an example of validation, specifically `:linkContentType`?

**Comment by nomasprime** [comment]
This worked, the rough cut:
```
create_content_type("Splash Banner") do |content_type|
  content_type.field("Text", :symbol)
  content_type.field("Image", :asset_link)
  field = content_type.field("Form", :entry_link)
  validation = Contentful::Management::Validation.new
  validation.link_content_type = ["5X9qaQUT1SgOc4Wsk88euG"]
  field.validations = [validation]
end.publish
```

**Comment by dlitvakb** [comment]
No problem!

Glad it worked!

Closing this issue.
