### ISSUE TITLE
Uploads and model association

### ISSUE THREAD

**Issue by nomasprime** [contentful/contentful_model#88]
Does anyone know how to do uploads and associate them with a model?

**Comment by dlitvakb** [comment]
Hey @nomasprime,

You need to get instantiate a management client, you can do so by doing:

```
management_client = AnyContentfulModelClass.management
```

Then, you need to follow the instructions here: https://github.com/contentful/contentful-management.rb#file-uploads

Then, you just add the asset to an existing entry containing an asset field.

Cheers

**Comment by nomasprime** [comment]
Great, was thinking along the same lines but didn't know how to get the management object.

Thanks @dlitvakb 👍

**Comment by dlitvakb** [comment]
No problem!

Cheers

**Comment by nomasprime** [comment]
@dlitvakb tried this:
```ruby
ContentfulModel::Base.management.uploads.create(ContentfulModel.configuration.space, @asset)
```
But returns `nil`.

**Comment by dlitvakb** [comment]
Hey @nomasprime,

`uploads.create` takes either a `String` or a `File` object, therefore, you need to call `#to_path` on your asset.

```ruby
 ContentfulModel::Base.management.uploads.create(
  ContentfulModel.configuration.space,
  @asset.to_path
)
```

Please let me know if this works,

Cheers

**Comment by nomasprime** [comment]
Thanks @dlitvakb. Before I tried `to_path`, `to_realpath`, and `to_s`. It didn't work but was all out of ideas so I tried it again and it works.

Wish I could say why but I have absolutely no idea 😄

**Comment by dlitvakb** [comment]
I've personally never used `Pathname` that much, so I'm not entirely sure how it works, maybe you can try opening the file with the `'rb'` flag, and send the file object (this is supported).

Do you have `raise_errors` set to true on the SDK? The default when using the `::management` method is `true`.

Other than trying that I'm quite uncertain of what could be going on, as the SDK should either return a `Contentful::Management::Upload` object or raise an exception if there was a problem.

Cheers

**Comment by nomasprime** [comment]
@dlitvakb yep, errors are on.

The thing is I have this test:
```ruby
RSpec.describe ContentfulAsset do
  subject(:contentful_asset) { described_class.new }

  before do
    stub_request(
      :post, "https://upload.contentful.com/spaces/y354zno73dyd/uploads"
    ).to_return(status: 200, body: "", headers: {})
  end

  describe "#create" do
    it "uploads the file" do
      contentful_asset.create(file_fixture("everything-is-possible.jpg").to_s)

      expect(WebMock).to have_requested(:post, "https://upload.contentful.com/spaces/y354zno73dyd/uploads")
    end
```
With this code:
```ruby
class ContentfulAsset
  def create(asset)
    @asset = asset
    upload
  end

  private

  def create_file

  end

  def upload
    upload = ContentfulModel::Base.management.uploads.create(
      ContentfulModel.configuration.space,
      @asset
    )
    binding.pry
  end
end
```
Without WebMock I can get an upload object, with it I get `undefined method `[]' for nil:NilClass` from line 14 of the implementation.

Can you see what I'm doing wrong or maybe there's a better way to test this?

**Comment by dlitvakb** [comment]
Ahhh, now I understand your issue, you're returning an empty body, when actually an upload response looks something like this:https://github.com/contentful/contentful-management.rb/blob/master/spec/fixtures/vcr_cassettes/upload/create_file.yml#L61RL82

Cheers
