### ISSUE TITLE
.to_json() doesn't work because of a circular error somewhere

### ISSUE THREAD

**Issue by edtjones** [contentful/contentful_model#9]
It would be nice to be able to call `.to_json()` on a ContentfulModel object but it seems to fall over because somewhere there's a self-reference.

**Comment by skierkowski** [comment]
I just came across this same issue. My quick work-around was just to implement `to_hash` on the models, so when I call `to_json()` or `as_json()` it uses those hashes for serialization and avoids this error.

**Comment by dlitvakb** [comment]
Hey @skierkowski,

Could you explain what you did to solve this issue?

Also, when serialising do you want the original Raw representation of the entry or the internal representation by the gem?

For Raw representation, the entries already provide a method `#raw` which returns the hash from which the entry object was created.

**Comment by skierkowski** [comment]
In my code I have a `Category` and `Product` models which are associated (1-m), so I added this to my `Product` model. It's a simplified version of `#raw` which returns the min set needed by the client. I haven't tried using `#raw`, so it might work as well.

```ruby
def to_hash
  {
    id: id,
    title:  title,
    category: category.id,
    description: description,
    price: price,
    image: {
      id: image.id,
      url: "https:#{image.file.url}"
    }
  }
```

**Comment by dlitvakb** [comment]
Hey @skierkowski,

Thanks for the explanation!

Closing this issue.

Cheers

**Comment by dpikt** [comment]
I'm running into this error when using this library with https://github.com/fast-jsonapi/fast_jsonapi.  Since the class `respond_to?(:to_json)`, raising an exception is unexpected- can this be reopened?

**Comment by dpikt** [comment]
I'd be happy to submit a PR if so.
