### ISSUE TITLE
ContentfulModel 0.2.0 depends on Contentful 0.9.0 which is too old

### ISSUE THREAD

**Issue by rezonant** [contentful/contentful_model#92]
It looks like the repository has been updated to use newer versions of the Contentful gem. Is this work suitable for a release? We cannot depend on ContentfulModel 0.2.0 because of dependency issues, RubyGems installs 0.1.x instead, which has a bug related to model classes in modules. See #91 and #30

**Comment by rezonant** [comment]
Depending on the unreleased version of ContentfulModel is working for us. Also found out that `irbtools-more` seems to cause the `contentful` gem to lock up during `entries` queries, not sure why, we removed `irbtools-more` to solve that.

Gemfile:
```
gem 'contentful_model`, github: 'contentful/contentful_model`
```

**Comment by dlitvakb** [comment]
Hi @rezonant,

This is already fixed

**Comment by dlitvakb** [comment]
Hey @rezonant,

As you said, this has already been fixed for quite a while on the `master` branch.

We're looking forward to releasing the 1.0.0 version of this gem quite soon, I'm working on fixing everything that's pending on my bug queue. But I'm pretty close to done, and I'm quite hopeful that that date is before the end of the month.

Thanks for your contributions!

**Comment by dlitvakb** [comment]
Quick update on this,

I'm done with bug fixes, now adding one or two extra features before release.

Release is scheduled for May 2nd.

Cheers
