### ISSUE TITLE
Chainable queries should not use global state

### ISSUE THREAD

**Issue by rezonant** [contentful/contentful_model#94]
Right now, ContentfulModel accomplishes chainable queries by tracking the request parameters within a class variable on the model class being queried. This is not thread safe, and can lead to subtle but problematic bugs within client apps.

Instead, ContentfulModel should use a QueryBuilder pattern, like what ActiveRecord has with it's `Relation` class.

Simplest test case:
```ruby
MyModel.params(abc: 123)
puts MyModel.all.load.length
```

Expected result: Should output the length of the loaded entries. 
Actual result: Exception because `abc` is not a valid parameter to the Contentful API.

I've implemented this change on my fork in the `feature/safe-chainable-queries` branch. This breaks compatibility, and I've also changed `find_by` to be called `where` and implemented a new `find_by` in terms of `where` and `limit(1)` and adjusted all the tests to match. I can PR this but it will require a major version tick. While I'd love to see these changes in the mainline, I think instead a new minor version of the gem needs to be released as per #92 before merging in any incompatible changes.

See my branch at: https://github.com/rezonant/contentful_model/tree/feature/safe-chainable-queries

**Comment by dlitvakb** [comment]
Hey @rezonant,

This is amazing!

Thanks for the contribution,

We're finishing some work in the new Environments feature that's about to be publicly released (currently in beta). Before continuing development here, but we're looking forward to make a new additions to this gem soon.

Cheers

**Comment by dlitvakb** [comment]
Hey @rezonant,

I'm back into working in this gem, and this is currently the task I'm working on.

I've just checked your branch and looks quite similar to the approach I was going to go for.

I've added a few new things already in master which makes your branch incompatible, but I'll take inspiration on it and adapt it to what I have now.

Thanks!
